---
- name: Ensure UFW allows DNS requests from WireGuard clients
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "10.192.122.0/24"

- name: Ensure UFW allows WireGuard
  ufw:
    to_port: "{{ wireguard_port }}"
    proto: "udp"
    rule: "allow"

- name: Allow WireGuard through the firewall
  command: "{{ item }}"
  with_items: "{{ wireguard_firewall_rules }}"

- name: "Add WireGuard firewall persistence service to init"
  template:
    src: streisand-wireguard-service.sh.j2
    dest: /etc/init.d/homebrand-wireguard
    mode: 0755

- name: "Enable the homebrand-wireguard init service"
  service:
    name: homebrand-wireguard
    enabled: yes
